spring:
  datasource:
    url: jdbc:mysql://localhost:3306/okkyclone_db?characterEncoding=UTF-8&&serverTimezone=UTC
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create # 운영시에는 validate 추천
    show-sql: true