spring:
  devtools:
    livereload:
      enabled: true
  freemarker:
    cache: false
  thymeleaf:
    cache: false
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:mysql://localhost:3306/testerdb?serverTimezone=UTC
    username: tester
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver